DHTML_modalMessage=function(){
    var A;var G;var D;var L;var F;var C;var B;var M;var J;var K;var I;var E;var N;var H;this.url="";this.htmlOfModalMessage="";this.layoutCss="modal-message.css";this.height=290;this.width=400;this.cssClassOfMessageBox=false;this.shadowDivVisible=true;this.shadowOffset=5;this.MSIE=false;if(navigator.userAgent.indexOf("MSIE")>=0){
        this.MSIE=true
        }
    };DHTML_modalMessage.prototype={
    setSource:function(A){
        this.url=A
        },
    setHtmlContent:function(A){
        this.htmlOfModalMessage=A
        },
    setSize:function(B,A){
        if(B){
            this.width=B
            }if(A){
            this.height=A
            }
        },
    setCssClassMessageBox:function(A){
        this.cssClassOfMessageBox=A;if(this.divs_content){
            if(this.cssClassOfMessageBox){
                this.divs_content.className=this.cssClassOfMessageBox
                }else{
                this.divs_content.className="modalDialog_contentDiv"
                }
            }
        },
    setShadowOffset:function(A){
        this.shadowOffset=A
        },
    display:function(){
        if(!this.divs_transparentDiv){
            this.__createDivs()
            }this.divs_transparentDiv.style.display="block";this.divs_content.style.display="block";this.divs_shadow.style.display="block";if(this.MSIE){
            this.iframe.style.display="block"
            }this.__resizeDivs();window.refToThisModalBoxObj=this;setTimeout("window.refToThisModalBoxObj.__resizeDivs()",150);this.__insertContent()
        },
    setShadowDivVisible:function(A){
        this.shadowDivVisible=A
        },
    close:function(){
        this.divs_transparentDiv.style.display="none";this.divs_content.style.display="none";this.divs_shadow.style.display="none";if(this.MSIE){
            this.iframe.style.display="none"
            }
        },
    addEvent:function(B,A,C,D){
        if(!D){
            D=""
            }if(B.attachEvent){
            B["e"+A+C+D]=C;B[A+C+D]=function(){
                B["e"+A+C+D](window.event)
                };B.attachEvent("on"+A,B[A+C+D])
            }else{
            B.addEventListener(A,C,false)
            }
        },
    __createDivs:function(){
        this.divs_transparentDiv=document.createElement("DIV");this.divs_transparentDiv.className="modalDialog_transparentDivs";this.divs_transparentDiv.style.left="0px";this.divs_transparentDiv.style.top="0px";document.body.appendChild(this.divs_transparentDiv);this.divs_content=document.createElement("DIV");this.divs_content.className="modalDialog_contentDiv";this.divs_content.id="DHTMLSuite_modalBox_contentDiv";this.divs_content.style.zIndex=100000;if(this.MSIE){
            this.iframe=document.createElement('<IFRAME src="about:blank" frameborder=0>');this.iframe.style.zIndex=90000;this.iframe.style.position="absolute";document.body.appendChild(this.iframe)
            }document.body.appendChild(this.divs_content);this.divs_shadow=document.createElement("DIV");this.divs_shadow.className="modalDialog_contentDiv_shadow";this.divs_shadow.style.zIndex=95000;document.body.appendChild(this.divs_shadow);window.refToModMessage=this;this.addEvent(window,"scroll",function(A){
            window.refToModMessage.__repositionTransparentDiv()
            });this.addEvent(window,"resize",function(A){
            window.refToModMessage.__repositionTransparentDiv()
            })
        },
    __getBrowserSize:function(){
        var A=document.documentElement.clientWidth;var B=document.documentElement.clientHeight;var A,B;if(self.innerHeight){
            A=self.innerWidth;B=self.innerHeight
            }else{
            if(document.documentElement&&document.documentElement.clientHeight){
                A=document.documentElement.clientWidth;B=document.documentElement.clientHeight
                }else{
                if(document.body){
                    A=document.body.clientWidth;B=document.body.clientHeight
                    }
                }
            }return[A,B]
        },
    __resizeDivs:function(){
        var E=Math.max(document.body.scrollTop,document.documentElement.scrollTop);if(this.cssClassOfMessageBox){
            this.divs_content.className=this.cssClassOfMessageBox
            }else{
            this.divs_content.className="modalDialog_contentDiv"
            }if(!this.divs_transparentDiv){
            return
        }var D=Math.max(document.body.scrollTop,document.documentElement.scrollTop-100);var C=Math.max(document.body.scrollLeft,document.documentElement.scrollLeft);window.scrollTo(C,D);setTimeout("window.scrollTo("+C+","+D+");",10);this.__repositionTransparentDiv();var F=this.__getBrowserSize();var B=F[0];var H=F[1];this.divs_content.style.width=this.width+"px";this.divs_content.style.height=this.height+"px";var A=this.divs_content.offsetWidth;var G=this.divs_content.offsetHeight;this.divs_content.style.left=Math.ceil((B-A)/2)+"px";if(isCustomWindow){
            this.divs_content.style.top=(Math.ceil((H-G)/6)+E)+"px"
            }else{
            this.divs_content.style.top=(Math.ceil((H-G)/2)+E)+"px"
            }if(this.MSIE){
            this.iframe.style.left=this.divs_content.style.left;this.iframe.style.top=this.divs_content.style.top;this.iframe.style.width=this.divs_content.style.width;this.iframe.style.height=this.divs_content.style.height
            }this.divs_shadow.style.left=(this.divs_content.style.left.replace("px","")/1+this.shadowOffset)+"px";this.divs_shadow.style.top=(this.divs_content.style.top.replace("px","")/1+this.shadowOffset)+"px";this.divs_shadow.style.height=G+"px";this.divs_shadow.style.width=A+"px";if(!this.shadowDivVisible){
            this.divs_shadow.style.display="none"
            }
        },
    __repositionTransparentDiv:function(){
        this.divs_transparentDiv.style.top=Math.max(document.body.scrollTop,document.documentElement.scrollTop)+"px";this.divs_transparentDiv.style.left=Math.max(document.body.scrollLeft,document.documentElement.scrollLeft)+"px";var B=this.__getBrowserSize();var A=B[0];var C=B[1];this.divs_transparentDiv.style.width=A+"px";this.divs_transparentDiv.style.height=C+"px"
        },
    __insertContent:function(){
        if(this.url){
            ajax_loadContent("DHTMLSuite_modalBox_contentDiv",this.url)
            }else{
            this.divs_content.innerHTML=this.htmlOfModalMessage
            }
        }
    };